// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsoCPU() {
  return window['go']['main']['App']['GetUsoCPU']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hola() {
  return window['go']['main']['App']['Hola']();
}
